name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
      
      - name: Run backend tests
        run: |
          if [ -f backend/test_main.py ]; then python -m pytest backend/test_main.py; fi
        continue-on-error: true
      
      - name: Build Docker image
        run: |
          docker build -t local-devops-backend:latest ./backend
